POST http://localhost:3333/imoveis
Content-Type: application/json

{
    "title": "teste",
    "description": "teste",
    "duration": "teste"
}

###

GET http://localhost:3333/imoveis
Content-Type: application/json


###
POST http://localhost:3333/registerUser
Content-Type: application/json

{
    "email": "renandzn2fam@gmail.conm",
    "password": "123",
    "username": "renandznfam"
}

###

POST http://localhost:3333/listImmobile
Content-Type: application/json

{
  
}