POST http://localhost:3333/imoveis
Content-Type: application/json

{
    "title": "teste",
    "description": "teste",
    "duration": "teste"
}

###

GET http://localhost:3333/imoveis
Content-Type: application/json


###
POST http://localhost:3333/validLogin
Content-Type: application/json

{id: "d5d115ebd627438b8b68199035c07c2c"}

###

POST http://localhost:3333/listImmobile
Content-Type: application/json

{
  
}